### ISSUE TITLE
Performance issue with Emacs 24.3.91

### ISSUE THREAD

**Issue by YorkZ** [emacsorphanage/emacs-git-gutter#50]
With Emacs 24.3.91 (git commit "0f0917d") in Linux, when `git-gutter-mode` is turned on in a 3 MB bytes org-mode buffer, every operation slows down dramatically. With Emacs 24.3.1 (git commit "3a1ce06") however, the speed was acceptable. I know it might be hard to address the issue, I will appreciate it if you could have some idea on how I could help track down the issue. Thanks in advance.

**Comment by thomasf** [comment]
I'm on emacs-24 master,, 

This seems strage, a profile report of just about 20 seconds usage...

![image](https://cloud.githubusercontent.com/assets/330847/7683626/af51e6a4-fd80-11e4-9fce-e21b3fdf1200.png)

side note: Since a week or so I set emacs gc threshold to 200mb just to see what happens.. idk if that is affecting my allocation numbers....

**Comment by syohex** [comment]
I suppose there is no performance issue on latest machine. If you have issue about performance. Please buy high power machine or use other package.
